
package stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "CustomerControllerService", targetNamespace = "http://controller.soap_service.soap_test_project.net/", wsdlLocation = "http://localhost:8080/api/soap/CustomerService?wsdl")
public class CustomerControllerService
    extends Service
{

    private static final URL CUSTOMERCONTROLLERSERVICE_WSDL_LOCATION;
    private static final WebServiceException CUSTOMERCONTROLLERSERVICE_EXCEPTION;
    private static final QName CUSTOMERCONTROLLERSERVICE_QNAME = new QName("http://controller.soap_service.soap_test_project.net/", "CustomerControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/api/soap/CustomerService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMERCONTROLLERSERVICE_WSDL_LOCATION = url;
        CUSTOMERCONTROLLERSERVICE_EXCEPTION = e;
    }

    public CustomerControllerService() {
        super(__getWsdlLocation(), CUSTOMERCONTROLLERSERVICE_QNAME);
    }

    public CustomerControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMERCONTROLLERSERVICE_QNAME, features);
    }

    public CustomerControllerService(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMERCONTROLLERSERVICE_QNAME);
    }

    public CustomerControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMERCONTROLLERSERVICE_QNAME, features);
    }

    public CustomerControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CustomerWS
     */
    @WebEndpoint(name = "CustomerWSPort")
    public CustomerWS getCustomerWSPort() {
        return super.getPort(new QName("http://controller.soap_service.soap_test_project.net/", "CustomerWSPort"), CustomerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerWS
     */
    @WebEndpoint(name = "CustomerWSPort")
    public CustomerWS getCustomerWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controller.soap_service.soap_test_project.net/", "CustomerWSPort"), CustomerWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMERCONTROLLERSERVICE_EXCEPTION!= null) {
            throw CUSTOMERCONTROLLERSERVICE_EXCEPTION;
        }
        return CUSTOMERCONTROLLERSERVICE_WSDL_LOCATION;
    }

}
